# Generated by Django 4.0.3 on 2022-04-08 08:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donthuoc',
            name='ketLuan',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='trieuChungBenh',
            field=ckeditor.fields.RichTextField(max_length=255),
        ),
    ]
